#!/usr/bin/env ruby

# Generate project ctags
# system("find . -name '*.rb' | /usr/local/bin/ctags -f .tags -L -")
# system("/usr/local/bin/ctags -R -f .tags .")

# Generate gem ctags
if File.exist?('./Gemfile')
    require 'bundler'

    project_path = Dir.pwd.to_s
    gem_paths = Bundler.load.specs.map(&:full_gem_path).join(' ')
    puts "::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::"
    project_and_gems = project_path.concat(' ').concat(gem_paths)
    puts "::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::"
    system("/usr/local/bin/ctags -R -f .gemtags #{project_and_gems}")
end
