#!/usr/bin/env ruby

# Generate project ctags
# system("find . -name '*.rb' | /usr/local/bin/ctags -f .tags -L -")
# system("/usr/local/bin/ctags -R -f .tags .")

# Generate gem ctags
if File.exist?('./Gemfile')
    require 'bundler'

    project_path = Dir.pwd.to_s
    gempath = Bundler.load.specs.map(&:full_gem_path).join(' ')
    project_and_gems = project_path.concat('/app ').concat(gempath)
    system("/usr/local/bin/ctags -V -R --languages=ruby --exclude=.git \
           --exclude=log --exclude=eunis --exclude='*.coffee' -R -f \
           .tags #{project_and_gems}")
end
