development:
  adapter: postgresql
  encoding: unicode
  database: catalogue_development
  pool: 5
  host: localhost
  username: user
  password: pass

test: &test
  adapter: postgresql
  encoding: unicode
  database: catalogue_test
  pool: 5
  host: localhost
  username: user
  password: pass

production:
  adapter: sqlite3
  encoding: unicode
  database: catalogue_production.db
  pool: 5

cucumber:
  <<: *test
