development:
  adapter: postgresql
  encoding: unicode
  database: catalogue_development
  pool: 5
  host: 89.0.1.129
  username: user
  password: pass

test:
  adapter: postgresql
  encoding: unicode
  database: catalogue_test
  pool: 5
  host: 89.0.1.129
  username: user
  password: pass

production:
  adapter: postgresql
  encoding: unicode
  database: catalogue_production
  pool: 5
  host: 89.0.1.129
  username: user
  password: pass

cucumber:
  <<: *test
