mode: textareas
theme: advanced
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom

theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect"

# theme_advanced_buttons3_add:
#   - tablecontrols
#   - fullscreen
# plugins:
#   - table
#   - fullscreen
