require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SpeciesController do

  # This should return the minimal set of attributes required to create a valid
  # Specie. As you add validations to Specie, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SpeciesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all species as @species" do
      specie = Specie.create! valid_attributes
      get :index, {}, valid_session
      assigns(:species).should eq([specie])
    end
  end

  describe "GET show" do
    it "assigns the requested specie as @specie" do
      specie = Specie.create! valid_attributes
      get :show, {:id => specie.to_param}, valid_session
      assigns(:specie).should eq(specie)
    end
  end

  describe "GET new" do
    it "assigns a new specie as @specie" do
      get :new, {}, valid_session
      assigns(:specie).should be_a_new(Specie)
    end
  end

  describe "GET edit" do
    it "assigns the requested specie as @specie" do
      specie = Specie.create! valid_attributes
      get :edit, {:id => specie.to_param}, valid_session
      assigns(:specie).should eq(specie)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Specie" do
        expect {
          post :create, {:specie => valid_attributes}, valid_session
        }.to change(Specie, :count).by(1)
      end

      it "assigns a newly created specie as @specie" do
        post :create, {:specie => valid_attributes}, valid_session
        assigns(:specie).should be_a(Specie)
        assigns(:specie).should be_persisted
      end

      it "redirects to the created specie" do
        post :create, {:specie => valid_attributes}, valid_session
        response.should redirect_to(Specie.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved specie as @specie" do
        # Trigger the behavior that occurs when invalid params are submitted
        Specie.any_instance.stub(:save).and_return(false)
        post :create, {:specie => {}}, valid_session
        assigns(:specie).should be_a_new(Specie)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Specie.any_instance.stub(:save).and_return(false)
        post :create, {:specie => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested specie" do
        specie = Specie.create! valid_attributes
        # Assuming there are no other species in the database, this
        # specifies that the Specie created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Specie.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => specie.to_param, :specie => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested specie as @specie" do
        specie = Specie.create! valid_attributes
        put :update, {:id => specie.to_param, :specie => valid_attributes}, valid_session
        assigns(:specie).should eq(specie)
      end

      it "redirects to the specie" do
        specie = Specie.create! valid_attributes
        put :update, {:id => specie.to_param, :specie => valid_attributes}, valid_session
        response.should redirect_to(specie)
      end
    end

    describe "with invalid params" do
      it "assigns the specie as @specie" do
        specie = Specie.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Specie.any_instance.stub(:save).and_return(false)
        put :update, {:id => specie.to_param, :specie => {}}, valid_session
        assigns(:specie).should eq(specie)
      end

      it "re-renders the 'edit' template" do
        specie = Specie.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Specie.any_instance.stub(:save).and_return(false)
        put :update, {:id => specie.to_param, :specie => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested specie" do
      specie = Specie.create! valid_attributes
      expect {
        delete :destroy, {:id => specie.to_param}, valid_session
      }.to change(Specie, :count).by(-1)
    end

    it "redirects to the species list" do
      specie = Specie.create! valid_attributes
      delete :destroy, {:id => specie.to_param}, valid_session
      response.should redirect_to(species_url)
    end
  end

end
